### ISSUE TITLE
Dualshock3 (sixaxis) A B X Y errors

### ISSUE THREAD

**Issue by dewiweb** [IBM/sdl2-gamecontroller#15]
I'll test your node with tour lenghty example on linux with a dualshock3 sixaxis controller:
All works except A,B, X and Y buttons throwing error 👍🏿 
```
player undefined pressed A
/home/dewi/Documents/GitHub/sdl2/node_modules/sdl2-gamecontroller/index.js:12
  gamecontroller.pollEvents();
                 ^

Error: Wrong arguments
    at SdlGameController.<anonymous> (/home/dewi/Documents/GitHub/sdl2/index.js:15:18)
    at SdlGameController.emit (events.js:315:20)
    at Timeout._onTimeout (/home/dewi/Documents/GitHub/sdl2/node_modules/sdl2-gamecontroller/index.js:12:18)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
```

**Comment by dewiweb** [comment]
another error on motion click:
`player undefined pressed leftstick
/home/dewi/Documents/GitHub/sdl2/index.js:54
      gamecontroller.setLeds(0x0f, 0x62, 0xfe, data.player);
                     ^

Error: Wrong arguments
    at SdlGameController.<anonymous> (/home/dewi/Documents/GitHub/sdl2/index.js:54:22)
    at SdlGameController.emit (events.js:315:20)
    at SdlGameController.pollEvents (<anonymous>)
    at Timeout._onTimeout (/home/dewi/Documents/GitHub/sdl2/node_modules/sdl2-gamecontroller/index.js:12:18)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)`

**Comment by dewiweb** [comment]
in fact , I'd just have to comment unsupported features... 
Make errors and learn
